---
title: "Fisheries"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
library(tidyverse)
fisheries <- read_csv("data/fisheries.csv")
continents <- read_csv("data/continents.csv")
```

The code below brings you to the point in the slides where we left off...

```{r}
fisheries <- fisheries %>%
  filter(total > 100000) %>%
  left_join(continents) %>%
  mutate(
    continent = case_when(
      country == "Democratic Republic of the Congo" ~ "Africa",
      country == "Hong Kong"                        ~ "Asia",
      country == "Myanmar"                          ~ "Asia",
      TRUE                                          ~ continent
      ),
    aquaculture_perc = aquaculture / total
    )
```

Create a new data frame called `fisheries_summary` that calculates minimum, 
mean, and maximum aquacultute percentage for each continent in the dataset 
and orders the results in descending order of mean aquaculture percentage.

```{r fisheries-summary}
# add your code here
```


