---
title: "Cumulative deaths from COVID-19"
date: "`r Sys.Date()`"
runtime: shiny
output: html_document
---

Countries around the world are responding to an outbreak of respiratory illness caused by a novel coronavirus, COVID-19. The outbreak first started in Wuhan, China, but cases have been identified in a growing number of other locations internationally, including the United States. In this report we explore how the trajectory of the cumulative deaths in a number of countries.

The data come from the **coronavirus** package, which pulls data from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus repository. The coronavirus package provides a tidy format dataset of the 2019 Novel Coronavirus COVID-19 (2019-nCoV) epidemic. The package is available on GitHub [here](https://github.com/RamiKrispin/coronavirus) and is updated daily.

Use the following app to customize the visualisation for countries of your choosing.

```{r app, echo=FALSE, warning=FALSE, message=FALSE}
library(shiny)
library(coronavirus)
library(tidyverse)
library(ggrepel)
library(glue)

selectInput(
  inputId = "country",
  label = "Select country (or countries)",
  choices = coronavirus %>% distinct(Country.Region) %>% as.vector(),
  selected = c("China", "France", "United Kingdom", "US", "Turkey"),
  multiple = TRUE
)

country_data <- reactive({
  coronavirus %>%
    # filter for deaths in countries of interest
    filter(
      type == "death",
      Country.Region %in% input$country
    ) %>%
    # fix county labels for pretty plotting
    mutate(
      country = case_when(
        Country.Region == "United Kingdom" ~ "UK",
        TRUE ~ Country.Region
      )
    ) %>%
    # calculate cumulative cases
    group_by(country, date) %>%
    summarise(tot_cases = sum(cases)) %>%
    arrange(date) %>%
    mutate(cumulative_cases = cumsum(tot_cases)) %>%
    # only use data where cumulative cases > 10
    filter(cumulative_cases > 9) %>%
    # calculate days elapsed and label for last recorded date for country
    mutate(
      days_elapsed = as.numeric(date - min(date)),
      end_label = ifelse(date == max(date), country, NA)
    )
})

as_of_date <- reactive({
  format(max(country_data()$date), "%A, %B %e, %Y")
})

last_data_point <- reactive({
  country_data() %>%
    group_by(country) %>%
    filter(date == max(date))
})

renderPlot({
  ggplot(data = country_data(),
         mapping = aes(
           x = days_elapsed,
           y = cumulative_cases,
           color = country,
           label = end_label
         )) +
    geom_line(size = 0.7, alpha = 0.8) +
    scale_color_viridis_d() +
    guides(color = FALSE) +
    geom_label_repel(nudge_y = 1, direction = "y", hjust = 1) +
    geom_point(data = last_data_point(), 
               mapping = aes(x = days_elapsed, 
                             y = cumulative_cases)) +
    theme_minimal() +
    labs(
      x = "Days since 10th confirmed death",
      y = "Cumulative number of deaths",
      title = "Cumulative deaths from COVID-19, selected countries",
      subtitle = glue("Data as of", as_of_date(), .sep = " "),
      caption = "Source: github.com/RamiKrispin/coronavirus"
    )
})
```
